run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - gofmt
    - staticcheck
    - unused
    - typecheck

issues:
  exclude-use-default: false

linters-settings:
  gofmt:
    simplify: true

  errcheck:
    check-type-assertions: true

  staticcheck:
    checks: ["all"]

  unused:
    check-exported: true
