Name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "helm/**"
    jobs:
      build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Set up Go 1.22
          uses: actions/setup-go@v2
          with:
            go-version: 1.22  # Use the latest Go version

        - name: Build
          run: go build -o go-web-app

        - name: Test 
          run: go test ./...  # Run all tests in the project-)

      code-quality:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Run golangci-lint 
          uses: golangci/golangci-lint-action@v3
          with:
            version: v1.56.2
      
  push:
    runs-on: ubuntu-latest
    needs: build  

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up docker buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and Push to dockerhub registry action
      uses: docker/build-push-action@v6
      with:
        context:
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/go-web-app:{{ github.run_id }}

  update-newtag-in-helm-chart:
    runs-on: ubuntu_latest

    needs: push
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
       token: ${{ secrets.TOKEN }}

    - name: Update tag in helm chart
      run: |
        sed -i "s/tag: .*/tag: \"${{ github.run_id }}\"/" helm/go-web-app-chart/values.yaml


    - name: Commit and push changes
      run:
        git config --global user.email "surisetty08@gmail.com"
        git config --global user.name "SurisettyGit"
        git add helm/go-web-app-chart/values.yaml
        git commit -m "Update tag in hel chart"
        git push
